// Generated by gencpp from file robot_commander/GetCoordsRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMANDER_MESSAGE_GETCOORDSREQUEST_H
#define ROBOT_COMMANDER_MESSAGE_GETCOORDSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_commander
{
template <class ContainerAllocator>
struct GetCoordsRequest_
{
  typedef GetCoordsRequest_<ContainerAllocator> Type;

  GetCoordsRequest_()
    : top_left()
    , bottom_right()  {
    }
  GetCoordsRequest_(const ContainerAllocator& _alloc)
    : top_left(_alloc)
    , bottom_right(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _top_left_type;
  _top_left_type top_left;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _bottom_right_type;
  _bottom_right_type bottom_right;





  typedef boost::shared_ptr< ::robot_commander::GetCoordsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_commander::GetCoordsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCoordsRequest_

typedef ::robot_commander::GetCoordsRequest_<std::allocator<void> > GetCoordsRequest;

typedef boost::shared_ptr< ::robot_commander::GetCoordsRequest > GetCoordsRequestPtr;
typedef boost::shared_ptr< ::robot_commander::GetCoordsRequest const> GetCoordsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_commander::GetCoordsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_commander::GetCoordsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_commander

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_commander::GetCoordsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_commander::GetCoordsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_commander::GetCoordsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_commander::GetCoordsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_commander::GetCoordsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_commander::GetCoordsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_commander::GetCoordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b9f4e3329747e348a5ae40cdd0c24ee";
  }

  static const char* value(const ::robot_commander::GetCoordsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b9f4e3329747e34ULL;
  static const uint64_t static_value2 = 0x8a5ae40cdd0c24eeULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_commander::GetCoordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_commander/GetCoordsRequest";
  }

  static const char* value(const ::robot_commander::GetCoordsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_commander::GetCoordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] top_left\n\
float32[] bottom_right\n\
";
  }

  static const char* value(const ::robot_commander::GetCoordsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_commander::GetCoordsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.top_left);
      stream.next(m.bottom_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCoordsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_commander::GetCoordsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_commander::GetCoordsRequest_<ContainerAllocator>& v)
  {
    s << indent << "top_left[]" << std::endl;
    for (size_t i = 0; i < v.top_left.size(); ++i)
    {
      s << indent << "  top_left[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.top_left[i]);
    }
    s << indent << "bottom_right[]" << std::endl;
    for (size_t i = 0; i < v.bottom_right.size(); ++i)
    {
      s << indent << "  bottom_right[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.bottom_right[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMANDER_MESSAGE_GETCOORDSREQUEST_H
