// Generated by gencpp from file path_planner/GetPoints.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_GETPOINTS_H
#define PATH_PLANNER_MESSAGE_GETPOINTS_H

#include <ros/service_traits.h>


#include <path_planner/GetPointsRequest.h>
#include <path_planner/GetPointsResponse.h>


namespace path_planner
{

struct GetPoints
{

typedef GetPointsRequest Request;
typedef GetPointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPoints
} // namespace path_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_planner::GetPoints > {
  static const char* value()
  {
    return "5627a41c994a8a6c1c220d190cfef6d1";
  }

  static const char* value(const ::path_planner::GetPoints&) { return value(); }
};

template<>
struct DataType< ::path_planner::GetPoints > {
  static const char* value()
  {
    return "path_planner/GetPoints";
  }

  static const char* value(const ::path_planner::GetPoints&) { return value(); }
};


// service_traits::MD5Sum< ::path_planner::GetPointsRequest> should match 
// service_traits::MD5Sum< ::path_planner::GetPoints > 
template<>
struct MD5Sum< ::path_planner::GetPointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::GetPoints >::value();
  }
  static const char* value(const ::path_planner::GetPointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::GetPointsRequest> should match 
// service_traits::DataType< ::path_planner::GetPoints > 
template<>
struct DataType< ::path_planner::GetPointsRequest>
{
  static const char* value()
  {
    return DataType< ::path_planner::GetPoints >::value();
  }
  static const char* value(const ::path_planner::GetPointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_planner::GetPointsResponse> should match 
// service_traits::MD5Sum< ::path_planner::GetPoints > 
template<>
struct MD5Sum< ::path_planner::GetPointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::GetPoints >::value();
  }
  static const char* value(const ::path_planner::GetPointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::GetPointsResponse> should match 
// service_traits::DataType< ::path_planner::GetPoints > 
template<>
struct DataType< ::path_planner::GetPointsResponse>
{
  static const char* value()
  {
    return DataType< ::path_planner::GetPoints >::value();
  }
  static const char* value(const ::path_planner::GetPointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_GETPOINTS_H
